application: base-app
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /images
  static_dir: static/images
- url: /fonts
  static_dir: static/fonts
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
